services:
  webapp:
    command: /app/entrypoint.sh --dev
    volumes:
      - type: bind
        source: ./src/dvm
        target: /app/src/dvm
  worker:
    volumes:
      - type: bind
        source: ./src/dvm
        target: /app/src/dvm
  adminer:
    image: adminer
    container_name: dvm_adminer
    restart: always
    ports:
      - 8080:8080
