version: '3.3'
services:
  webapp:
    command: /app/entrypoint.sh --dev
    volumes:
      - type: bind
        source: .
        target: /app
  worker:
    volumes:
      - type: bind
        source: .
        target: /app
  adminer:
    image: adminer
    container_name: dvm_adminer
    restart: always
    ports:
      - 8080:8080
