version: "3.3"
services:
  webapp:
    image: unocifra/porpoise:latest
    container_name: drone-video-measure-container
    ports:
      - "5000:5000"
    volumes:
      - appmedia:/app/data

volumes:
  appmedia:
