services:
  webapp:
    build: .
    pull_policy: build
    command: /app/entrypoint.sh --dev
    volumes:
      - type: bind
        source: ./src/dvm
        target: /app/src/dvm
      - type: bind
        source: ./data
        target: /app_data
  worker:
    build: .
    pull_policy: build
    command: "watchfiles --filter python 'celery -A dvm.make_celery worker --loglevel=WARNING -c 1' /app/src/dvm"
    volumes:
      - type: bind
        source: ./src/dvm
        target: /app/src/dvm
      - type: bind
        source: ./data
        target: /app_data
  adminer:
    image: adminer
    container_name: dvm_adminer
    restart: always
    ports:
      - 8080:8080
