version: '3.3'
services:
  webapp:
    command: python app.py runserver --host 0.0.0.0 --debug
    volumes:
      - type: bind
        source: .
        target: /app
  worker:
    volumes:
      - type: bind
        source: .
        target: /app
  adminer:
    image: adminer
    container_name: dvm_adminer
    restart: always
    ports:
      - 8080:8080
