version: '3.3'
services:
  webapp:
    build: .
    image: dvm
    container_name: dvm_app
    command: gunicorn -b 0.0.0.0:5000 -k gevent -t 10000 "app:app"
    ports:
      - "5000:5000"
    volumes:
      - appmedia:/app/data
    depends_on:
      - redis
      - worker
      - db
  worker:
    build: .
    container_name: dvm_worker
    command: celery -A app.celery worker --loglevel=WARNING -c 1
    volumes:
      - appmedia:/app/data
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: dvm_redis
  db:
    image: postgres:12-alpine
    container_name: dvm_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  
volumes:
  appmedia:
