version: '3.3'
services:
  webapp:
    image: midtiby/dronevideomeasure_webapp
    container_name: dvm_app
    command: /app/entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ../data
        target: /app/data
    depends_on:
      - redis
      - worker
      - db
  worker:
    image: midtiby/dronevideomeasure_webapp
    container_name: dvm_worker
    command: celery -A app.celery worker --loglevel=WARNING -c 1
    volumes:
      - type: bind
        source: ../data
        target: /app/data
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: dvm_redis
  db:
    image: postgres:12-alpine
    container_name: dvm_db
    volumes:
      - type: volume
        source: dvm_dbdata
        target: /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example

volumes:
  dvm_dbdata:
