"""Added takeoff altitude to the video object

Revision ID: 1c01da02bcd0
Revises: 8aa202e6821d
Create Date: 2023-08-01 10:12:29.441740

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c01da02bcd0"
down_revision = "8aa202e6821d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("video", schema=None) as batch_op:
        batch_op.add_column(sa.Column("takeoff_altitude", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("video", schema=None) as batch_op:
        batch_op.drop_column("takeoff_altitude")

    # ### end Alembic commands ###
